BoxLayoutExample:

<BoxLayoutExample>:
    orientation: "vertical"
    Button:
        text: "A"
    Button:
        text: "B"
    Label:
        text: "C"

<MainWidget>:
    Button:
        text: "Hello"
        size: "40dp", "40dp"
        pos: "10dp", "200dp"
        color: 0, 0, 1, 1
    Label:
        text: "Hello2"
        size: "50dp", "40dp"
        pos: "50dp", "300dp"
        color: 1, 0, 0, 1